import 'package:flutter/material.dart';
import 'package:get/get.dart';

class AppsInfoController extends GetxController{

  static List<Map> map = [
    { "appname": "HTML Creator",
      "appversion": "7.0",
      "icon": "hc.png",
      "appbarcolor": const Color(0xFF0D0C11),
      "bodycolor": const Color(0xFF1C1B1F),
      "appdescription": "The HTML Creator app, available on Google Play and the App Store, provides a versatile platform for writing and testing HTML, CSS, and JavaScript code offline. It offers valuable features including color coding, fast code layout tools, and shortcuts for efficient coding, enhancing the development experience. Users can also access demo projects for learning and reference, making it a handy tool for web developers and enthusiasts on mobile devices.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.htmleditor",
      "appstorelink": "https://apps.apple.com/in/app/html-creator/id1660005856"
    },
    { "appname": "Java Compiler",
      "appversion": "3.0",
      "icon": "jc.png",
      "appbarcolor": const Color(0xFF0D0C11),
      "bodycolor": const Color(0xFF1C1B1F),
      "appdescription": "The Java Compiler app, available on both Google Play and the App Store, offers a platform for writing, compiling, and running Java code on mobile devices. Users can conveniently develop and test Java applications with features such as code highlighting and error checking, making it a versatile tool for Java programmers.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.javacompiler",
      "appstorelink": "https://apps.apple.com/in/app/java-compiler/id1667096796"
    },
    { "appname": "Python Compiler",
      "appversion": "2.0",
      "icon": "pc.png",
      "appbarcolor": const Color(0xFF0D0C11),
      "bodycolor": const Color(0xFF1C1B1F),
      "appdescription": "The Python Compiler app, accessible on both Google Play and the App Store, offers a platform for writing, compiling, and running Python code on mobile devices. Users can conveniently develop and test Python applications with features such as code highlighting and error checking, making it a versatile tool for Python programmers.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.pythoncompiler",
      "appstorelink": "https://apps.apple.com/in/app/python-compiler/id1668082899"
    },
    { "appname": "C Compiler",
      "appversion": "2.0",
      "icon": "cc.png",
      "appbarcolor": const Color(0xFF0D0C11),
      "bodycolor": const Color(0xFF1C1B1F),
      "appdescription": "The C Compiler app, accessible on both Google Play and the App Store, offers a platform for writing, compiling, and running C code on mobile devices. Users can conveniently develop and test C applications with features such as code highlighting and error checking, making it a versatile tool for C programmers.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.ccompiler",
      "appstorelink": "https://apps.apple.com/in/app/c-compiler%E3%85%A4%E3%85%A4/id1669070714"
    },
    { "appname": "C# Compiler",
      "appversion": "1.0",
      "icon": "csc.png",
      "appbarcolor": const Color(0xFF0D0C11),
      "bodycolor": const Color(0xFF1C1B1F),
      "appdescription": "The C# Compiler app, available on both Google Play and the App Store, offers a platform for writing, compiling, and running C# code on mobile devices. Users can conveniently develop and test C# applications with features such as code highlighting and error checking, making it a versatile tool for C# programmers.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.anvaysoft.csharpcompiler",
      "appstorelink": "https://apps.apple.com/in/app/c-sharp-compiler/id6670162788"
    },
    { "appname": "C++ Compiler",
      "appversion": "2.0",
      "icon": "cppc.png",
      "appbarcolor": const Color(0xFF0D0C11),
      "bodycolor": const Color(0xFF1C1B1F),
      "appdescription": "The C++ Compiler app, available on both Google Play and the App Store, offers a platform for writing, compiling, and running C++ code on mobile devices. Users can conveniently develop and test C++ applications with features such as code highlighting and error checking, making it a versatile tool for C++ programmers.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.cppcompiler",
      "appstorelink": "https://apps.apple.com/in/app/c-compiler/id6447482958"
    },
    { "appname": "BackWalls",
      "appversion": "1.8",
      "icon": "bw.png",
      "appbarcolor": Colors.blue,
      "bodycolor": Colors.white,
      "appdescription": "BackWalls is a wallpaper app available on Google Play and the App Store. It offers a vast collection of high-quality wallpapers across various categories, allowing users to personalize their device's backgrounds with stunning visuals. Users can easily browse, select, and download wallpapers to enhance their mobile device's aesthetics.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.walls",
      "appstorelink": "https://apps.apple.com/in/app/backwalls/id1672657308"
    },
    { "appname": "ToolKit",
      "appversion": "4.1",
      "icon": "tk.png",
      "appbarcolor": Colors.green,
      "bodycolor": Colors.white,
      "appdescription": "The Toolkit app, available on both Google Play and the App Store, is a versatile toolset designed to enhance the WhatsApp experience. It provides a range of features such as text repeater, text to emoji conversion, direct messaging, WhatsWeb functionality, circular image creation, text reversal, and more.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.toolkit",
      "appstorelink": "https://apps.apple.com/in/app/%E3%85%A4toolkit%E3%85%A4%E3%85%A4%E3%85%A4/id6448226564"
    },
    { "appname": "Image Rounder",
      "appversion": "1.0",
      "icon": "ir.png",
      "appbarcolor": Colors.red,
      "bodycolor": Colors.white,
      "appdescription": "The Image Rounder app, accessible on both Google Play and the App Store, is a straightforward tool designed to round the corners of images. It simplifies the process of adding rounded edges to pictures, enhancing their visual appeal.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.imagerounder",
      "appstorelink": "https://apps.apple.com/in/app/image-rounder%E3%85%A4/id6448722040"
    },
    { "appname": "QuickChart",
      "appversion": "1.1",
      "icon": "qc.png",
      "appbarcolor": Colors.white,
      "bodycolor": Colors.white,
      "appdescription": "The QuickChart app, available on both Google Play and the App Store, is a user-friendly tool for swiftly generating various types of charts. It simplifies the chart creation process by allowing users to input data entries, and it can produce different types of charts such as bar chart, pie chart, line chart, and more.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.quickchart",
      "appstorelink": "https://apps.apple.com/in/app/quickchart%E3%85%A4/id6450350265"
    },
    { "appname": "AudioBook",
      "appversion": "1.5",
      "icon": "ab.png",
      "appbarcolor": Colors.indigo,
      "bodycolor": Colors.white,
      "appdescription": "The AudioBook app, accessible on Google Play and the App Store, allows users to seamlessly convert text into audio files, enabling text-to-speech functionality. Furthermore, it offers the capability to generate audio documents from text and provides scanning features to extract text from physical pages, making it a versatile tool for creating, sharing, and accessing audio content from written materials.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.audiobook",
      "appstorelink": "https://apps.apple.com/in/app/audiobook%E3%85%A4/id6453291738"
    },
    { "appname": "FlutterLab",
      "appversion": "1.0",
      "icon": "fl.png",
      "appbarcolor": Colors.grey[850],
      "bodycolor": Colors.grey[850],
      "appdescription": "The FlutterLab is an educational app available on Google Play and the App Store, offering an extensive Flutter course. It covers installation steps, Dart core concepts, in-depth widget explanations, database integration, and even guides on integrating ads. With over 60 chapters, code samples, interactive previews, and hands-on projects, it's a comprehensive resource for learning and mastering Flutter development.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.flutterlab",
      "appstorelink": "https://apps.apple.com/in/app/flutterlab/id6464216661"
    },
    { "appname": "Images to PDF",
      "appversion": "1.1",
      "icon": "itp.png",
      "appbarcolor": Colors.indigo,
      "bodycolor": Colors.white,
      "appdescription": "Transform your collection of images into professional PDF documents with Images to PDF! This versatile and user-friendly app empowers you to effortlessly convert your photos, scanned documents, or any image files into PDFs, all while offering a range of powerful features to enhance your PDF creation experience.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.techbajao.imagestopdf",
      "appstorelink": "https://apps.apple.com/in/app/imagestopdf/id6468679343"
    },
    { "appname": "PDF Guard",
      "appversion": "1.0",
      "icon": "pg.png",
      "appbarcolor": Colors.teal,
      "bodycolor": Colors.white,
      "appdescription": "PDF Guard: Your Ultimate Solution for PDF Security and Freedom. Easily lock and unlock your PDF files with precision and confidence. Take control of your document privacy and accessibility in just a few clicks. Guard your information, unlock your convenience.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.anvaysoft.pdfguard",
      "appstorelink": "https://apps.apple.com/in/app/pdfguard/id6475248978"
    },
    { "appname": "SQL Playground",
      "appversion": "1.0",
      "icon": "sp.png",
      "appbarcolor": Colors.grey[800],
      "bodycolor": Colors.grey[850],
      "appdescription": "SQL Playground: Execute queries effortlessly with multiple database support, table customization, and intuitive shortcuts. Import/export data seamlessly, and enhance readability with color coding. Effortlessly export results as CSV for efficient data sharing and analysis.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.anvaysoft.sqlplayground",
      "appstorelink": "https://apps.apple.com/in/app/sqlplayground/id6477329554"
    },
    { "appname": "Background Creator",
      "appversion": "1.0",
      "icon": "bc.png",
      "appbarcolor": const Color(0xFF4f378b),
      "bodycolor": Colors.grey[50],
      "appdescription": "Craft personalized solid backgrounds effortlessly. Choose from a spectrum of custom hex colors and define your preferred dimensions, all while adding a touch of elegance with adjustable border radius settings. Redefine your digital canvas with just a few clicks.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.anvaysoft.backgroundcreator",
      "appstorelink": "https://apps.apple.com/in/app/backgroundcreator/id6479609704"
    },
    { "appname": "Icon Creator",
      "appversion": "1.0",
      "icon": "ic.png",
      "appbarcolor": const Color(0xFF1C1B20),
      "bodycolor": const Color(0xFF1C1B20),
      "appdescription": "Icon Creator offers a versatile platform for crafting icons and logos. With a vast library, customizable properties, and support for layers, users can effortlessly design unique graphics tailored to their specifications.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.anvaysoft.iconcreator",
      "appstorelink": "https://apps.apple.com/in/app/icon-creator/id6480472326"
    },
    { "appname": "API Tester",
      "appversion": "1.0",
      "icon": "at.png",
      "appbarcolor": const Color(0xFF0D0C11),
      "bodycolor": const Color(0xFF1C1B1F),
      "appdescription": "API Tester lets you test and manage APIs with ease. Organize request collections, customize headers, handle authentication, and share collections as .atc files. Learn API basics with in-app tutorials.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.anvaysoft.api_tester",
      "appstorelink": "https://apps.apple.com/in/app/api-tester/id6737351493"
    },
    { "appname": "AdmobDash",
      "appversion": "1.0",
      "icon": "ad.png",
      "appbarcolor": const Color(0xFF36618e),
      "bodycolor": const Color(0xFFFFFFFF),
      "appdescription": "AdmobDash is a simple and powerful app designed to help you track and analyze your AdMob earnings with ease. Its user-friendly interface provides all the information you need to monitor your revenue effectively.",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.anvaysoft.admobdash",
      "appstorelink": "https://apps.apple.com/in/app/admobdash/id6738627846"
    },
    { "appname": "JSON Viewer",
      "appversion": "1.0",
      "icon": "ad.png",
      "appbarcolor": Colors.indigo,
      "bodycolor": const Color(0xFFFFFFFF),
      "appdescription": "Simplify your JSON experience with JSON Viewer! Effortlessly view and edit JSON content with intuitive tools, fast navigation, and customizable text size. Boost productivity and streamline your workflow with ease!",
      "googleplaylink": "https://play.google.com/store/apps/details?id=com.anvaysoft.jsonviewer",
      "appstorelink": "https://apps.apple.com/in/app/json-viewer/id6740746338"
    },
  ];

}