// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGI9Hq1L-d27hkTFxta9GVIQxiXN54bE',
    appId: '1:592297377123:web:d799bfa9471ea2257ae756',
    messagingSenderId: '592297377123',
    projectId: 'projectjam-2d915',
    authDomain: 'projectjam-2d915.firebaseapp.com',
    databaseURL: 'https://projectjam-2d915-default-rtdb.firebaseio.com',
    storageBucket: 'projectjam-2d915.appspot.com',
    measurementId: 'G-7S4F92H3VN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhVWQYrjuHfEypRPju6Dzz12w4mbNndug',
    appId: '1:592297377123:android:86ab3fe6f12878b97ae756',
    messagingSenderId: '592297377123',
    projectId: 'projectjam-2d915',
    databaseURL: 'https://projectjam-2d915-default-rtdb.firebaseio.com',
    storageBucket: 'projectjam-2d915.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvZUxOdbvepqsRgh2OkJWUi7yBwE8YnJQ',
    appId: '1:592297377123:ios:e42ea6cc263ca0977ae756',
    messagingSenderId: '592297377123',
    projectId: 'projectjam-2d915',
    databaseURL: 'https://projectjam-2d915-default-rtdb.firebaseio.com',
    storageBucket: 'projectjam-2d915.appspot.com',
    iosClientId: '592297377123-39qqepsum9srtlh5s32fuj11u95ncdc9.apps.googleusercontent.com',
    iosBundleId: 'com.techbajao.anvaysoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvZUxOdbvepqsRgh2OkJWUi7yBwE8YnJQ',
    appId: '1:592297377123:ios:61001bd967ed7a917ae756',
    messagingSenderId: '592297377123',
    projectId: 'projectjam-2d915',
    databaseURL: 'https://projectjam-2d915-default-rtdb.firebaseio.com',
    storageBucket: 'projectjam-2d915.appspot.com',
    iosClientId: '592297377123-176voi2j2rdggr7rsa9en6jp6nuqdvhv.apps.googleusercontent.com',
    iosBundleId: 'com.techbajao.anvaysoft.RunnerTests',
  );
}
